// Code generated by MockGen. DO NOT EDIT.
// Source: loadstatementmodal.go

// Package mock_display is a generated GoMock package.
package mock_display

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoadStatementModalController is a mock of LoadStatementModalController interface.
type MockLoadStatementModalController struct {
	ctrl     *gomock.Controller
	recorder *MockLoadStatementModalControllerMockRecorder
}

// MockLoadStatementModalControllerMockRecorder is the mock recorder for MockLoadStatementModalController.
type MockLoadStatementModalControllerMockRecorder struct {
	mock *MockLoadStatementModalController
}

// NewMockLoadStatementModalController creates a new mock instance.
func NewMockLoadStatementModalController(ctrl *gomock.Controller) *MockLoadStatementModalController {
	mock := &MockLoadStatementModalController{ctrl: ctrl}
	mock.recorder = &MockLoadStatementModalControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoadStatementModalController) EXPECT() *MockLoadStatementModalControllerMockRecorder {
	return m.recorder
}

// OnLoadStatement mocks base method.
func (m *MockLoadStatementModalController) OnLoadStatement(csvFile, presetFile string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnLoadStatement", csvFile, presetFile)
}

// OnLoadStatement indicates an expected call of OnLoadStatement.
func (mr *MockLoadStatementModalControllerMockRecorder) OnLoadStatement(csvFile, presetFile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLoadStatement", reflect.TypeOf((*MockLoadStatementModalController)(nil).OnLoadStatement), csvFile, presetFile)
}
